### ISSUE TITLE
Add custom header

### ISSUE THREAD

**Issue by roberto-slopez** [STRML/node-xlsx-writestream#23]
I need to add a header with full date, before the table that is generated

Like this, 

| DATE: 9/17/2016, 1:21:34 PM |
|------

| NAME 	| CODE 	| DESCRIPTION 	| KEY 
|------	|------	|-------------	|-----	|
| A    	| 1    	| THE A       	| 01  	| 
| B    	| 2    	| THE B       	| 02  	|  
| B    	| 3    	| THE C       	| 03  	|

**Comment by JakeHamix** [comment]
Hi there, better late than never :)
I just needed something similar and ended up with this:

```javascript
// Inject headers as the first line
xlsxWriter.cellMap = keys;
xlsxWriter._write(blobs.sheetDataHeader);
xlsxWriter.haveHeader = true;

const headers = Object.fromEntries(_.zip(keys, names));
xlsxWriter.addRow(headers);
```
