### ISSUE TITLE
Inconsistent handling of number strings

### ISSUE THREAD

**Issue by guyonroche** [STRML/node-xlsx-writestream#4]
With the following code...
	var fs = require('fs');
	var XlsxWriter = require('xlsx-writestream');

	var filename = process.argv[2];

	var writer = new XlsxWriter('mySpreadsheet.xlsx', {} /* options */);
	writer.getReadStream().pipe(fs.createWriteStream(filename));

	writer.addRow({ "ID": "1", "Text": "Hello, World!" });
	writer.addRow({ "ID": "11", "Text": "Goodbye, World!" });

	writer.finalize();

...the ID column will have different cell types for the first and second data rows. The first is a number as string and the second matches the numberRegex (because it has two digits) and so is written as a number cell.

My preference is - don't get clever - the value passed in was a string, I wanted the cell type to be string also.

**Comment by STRML** [comment]
Fixed in 0.4.0.
